testing

diff --git a/.github/workflows/create-hetzner-server.yml b/.github/workflows/create-hetzner-server.yml
--- a/.github/workflows/create-hetzner-server.yml
+++ b/.github/workflows/create-hetzner-server.yml
@@ -120,8 +120,9 @@ jobs:
               -e "s#SSH_HOST#$SSH_HOST#" \
               > infrastructure/server-setup/inventory/${{ github.event.inputs.env_name }}.yml
           echo "Environment file created: infrastructure/server-setup/inventory/${{ github.event.inputs.env_name }}.yml"
-
-          ssh-keyscan -H "$SSH_HOST" >> infrastructure/known-hosts || echo "Failed to add $SSH_HOST to known_hosts"
+          grep -v "$SSH_HOST" > infrastructure/known-hosts.tmp
+          ssh-keyscan -H "$SSH_HOST" >> infrastructure/known-hosts.tmp || echo "Failed to add $SSH_HOST to known_hosts"
+          mv infrastructure/known-hosts.tmp infrastructure/known-hosts
 
       - env:
           SSH_HOST: ${{ steps.output.outputs.ssh_host }}
@@ -149,7 +150,6 @@ jobs:
             echo "Adding secret: $key"
             gh secret set $key --env ${{ github.event.inputs.env_name }} --body "$password"
           done < infrastructure/provision-server/templates/environment.secrets.tpl
-          ls -l $TF_PATH/.ssh/id_rsa
           gh secret set SSH_KEY --env ${{ github.event.inputs.env_name }} < $TF_PATH/.ssh/id_rsa || echo "Failed"
 
       - name: Commit and push changes
