testing

diff --git a/.github/workflows/create-hetzner-server.yml b/.github/workflows/create-hetzner-server.yml
--- a/.github/workflows/create-hetzner-server.yml
+++ b/.github/workflows/create-hetzner-server.yml
@@ -120,11 +120,25 @@ jobs:
               -e "s#SSH_HOST#$SSH_HOST#" \
               > infrastructure/server-setup/inventory/${{ github.event.inputs.env_name }}.yml
           echo "Environment file created: infrastructure/server-setup/inventory/${{ github.event.inputs.env_name }}.yml"
-          grep -v "$SSH_HOST" > infrastructure/known-hosts.tmp || echo "Failed grep?: $?"
+          grep -v "$SSH_HOST" infrastructure/known-hosts > infrastructure/known-hosts.tmp || echo "Failed grep?: $?"
           ssh-keyscan -H "$SSH_HOST" >> infrastructure/known-hosts.tmp || echo "Failed to add $SSH_HOST to known_hosts"
           echo "failed ssh scan?: $?"
           mv infrastructure/known-hosts.tmp infrastructure/known-hosts || echo "Last step?"
 
+          workflows=(
+            ".github/workflows/provision.yml"
+          )
+          path=".on.workflow_dispatch.inputs.environment.options"
+
+          # Check if option already exists
+          if ! yq e "$path" "$file" | grep -qx "${{ github.event.inputs.env_name }}"; then
+            echo "Adding new option: ${{ github.event.inputs.env_name }}"
+            for workflow in ${workflows[@]}
+            do
+              yq e "$path += [\"${{ github.event.inputs.env_name }}\"]" -i "$workflow"
+          else
+            echo "Option '$new_option' already exists"
+          fi
           echo "End"
 
       - env:
