testing

diff --git a/.github/workflows/create-hetzner-server.yml b/.github/workflows/create-hetzner-server.yml
--- a/.github/workflows/create-hetzner-server.yml
+++ b/.github/workflows/create-hetzner-server.yml
@@ -88,38 +88,37 @@ jobs:
       - run: |
           cp ${{ env.TF_PATH }}/terraform.tfstate terraform-state/${{ vars.COUNTRY_NAME }}/${{ inputs.env_name }}-${{ inputs.env_type }}.tfstate
           cd terraform-state/
+          git config --local user.name "OpenCRVS Bot"
+          git config --local user.email "bot@opencrvs.org"
           git add ${{ vars.COUNTRY_NAME }}/${{ inputs.env_name }}-${{ inputs.env_type }}.tfstate
           git commit -m "Add environment file for ${{ github.event.inputs.env_name }} env with type ${{ inputs.env_type }}"
           git push
 
-      # - name: Store variables
-      #   id: output
-      #   working-directory: ${{ env.TF_PATH }}
-      #   run: |
-      #     echo "ssh_host=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
-      #     echo "hostname=$TF_VAR_country_name-$TF_VAR_env_name" >> $GITHUB_OUTPUT
-      # # FIXME: We can upload artifact, but it useless for us
-      # - name: Upload Terraform state
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: terraform-state
-      #     path: ${{ env.TF_PATH }}/terraform.tfstate
+      - name: Store variables
+        id: output
+        working-directory: ${{ env.TF_PATH }}
+        run: |
+          if [ ${{ inputs.env_type }} == 'single-node' ]
+          then
+          echo "ssh_host=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
+          echo "hostname=$TF_VAR_country_name-$TF_VAR_env_name" >> $GITHUB_OUTPUT
+          fi
 
-      # - name: Create environment file
-      #   env:
-      #     SSH_HOST: ${{ steps.output.outputs.ssh_host }}
-      #     HOSTNAME: ${{ steps.output.outputs.hostname }}
-      #     # TODO: Fix hardcoded domain
-      #     DOMAIN: ${{ github.event.inputs.env_name }}.opencrvs.dev
-      #   run: |
-      #     mkdir -p infrastructure/server-setup/inventory
-      #     cat infrastructure/provision-server/templates/staging-env.yml | \
-      #     sed -e "s#HOSTNAME#$HOSTNAME#" \
-      #         -e "s#SSH_HOST#$SSH_HOST#" \
-      #         > infrastructure/server-setup/inventory/${{ github.event.inputs.env_name }}.yml
-      #     echo "Environment file created: infrastructure/server-setup/inventory/${{ github.event.inputs.env_name }}.yml"
-      # # - name: Update known_hosts
-      # #     ssh-keyscan -H "$SSH_HOST" >> infrastructure/known-hosts || echo "Failed to add $SSH_HOST to known_hosts"
+      - name: Create environment files
+        env:
+          SSH_HOST: ${{ steps.output.outputs.ssh_host }}
+          HOSTNAME: ${{ steps.output.outputs.hostname }}
+          # TODO: Fix hardcoded domain
+          DOMAIN: ${{ github.event.inputs.env_name }}.opencrvs.dev
+        run: |
+          mkdir -p infrastructure/server-setup/inventory
+          cat infrastructure/provision-server/templates/staging-env.yml | \
+          sed -e "s#HOSTNAME#$HOSTNAME#" \
+              -e "s#SSH_HOST#$SSH_HOST#" \
+              > infrastructure/server-setup/inventory/${{ github.event.inputs.env_name }}.yml
+          echo "Environment file created: infrastructure/server-setup/inventory/${{ github.event.inputs.env_name }}.yml"
+
+          ssh-keyscan -H "$SSH_HOST" >> infrastructure/known-hosts || echo "Failed to add $SSH_HOST to known_hosts"
 
       # - env:
       #     SSH_HOST: ${{ steps.output.outputs.ssh_host }}
